"""sprint9_alerts

Revision ID: 039e60eb1a72
Revises: a9c3f7e21b04
Create Date: 2026-09-22 16:45:38.404205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '039e60eb1a72'
down_revision: Union[str, Sequence[str], None] = 'a9c3f7e21b04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_channels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_channels_tenant_status'))

    op.drop_table('alerts')
    op.drop_table('alert_channels')

    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=36), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index('ix_alerts_tenant_status', ['tenant_id', 'status'], unique=False)
        batch_op.create_index('uix_alerts_incident_open', ['incident_id'], unique=True, sqlite_where=sa.text("status = 'OPEN'"), postgresql_where=sa.text("status = 'OPEN'"))

    op.create_table('alert_audit_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('alert_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_audit_records', schema=None) as batch_op:
        batch_op.create_index('ix_alert_audit_alert', ['alert_id'], unique=False)
        batch_op.create_index('ix_alert_audit_tenant', ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_channels',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('channel_type', sa.VARCHAR(length=32), nullable=False),
    sa.Column('configuration', sa.TEXT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_channels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_channels_tenant_status'), ['tenant_id', 'status'], unique=False)

    op.execute("DELETE FROM alert_audit_records")
    op.execute("DELETE FROM alerts")
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payload', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('channel_id', sa.VARCHAR(length=36), nullable=False))
        batch_op.create_foreign_key(None, 'alert_channels', ['channel_id'], ['id'])
        batch_op.drop_index('uix_alerts_incident_open', sqlite_where=sa.text("status = 'OPEN'"), postgresql_where=sa.text("status = 'OPEN'"))
        batch_op.create_index(batch_op.f('ix_alerts_tenant_incident'), ['tenant_id', 'incident_id'], unique=False)
        batch_op.drop_column('resolved_by')
        batch_op.drop_column('resolved_at')
        batch_op.drop_column('acknowledged_by')
        batch_op.drop_column('acknowledged_at')
        batch_op.drop_column('description')
        batch_op.drop_column('title')
        batch_op.drop_column('severity')

    with op.batch_alter_table('alert_audit_records', schema=None) as batch_op:
        batch_op.drop_index('ix_alert_audit_tenant')
        batch_op.drop_index('ix_alert_audit_alert')

    op.drop_table('alert_audit_records')
    # ### end Alembic commands ###
