"""add_identity_federation

Revision ID: 06a7dd6a9514
Revises: f929ce0b171e
Create Date: 2026-09-17 15:04:04.406751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06a7dd6a9514'
down_revision: Union[str, Sequence[str], None] = 'f929ce0b171e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_identity_providers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider_type', sa.String(length=50), nullable=False),
    sa.Column('issuer_url', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_federated_identities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['external_identity_providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'subject_id', name='uq_agent_federated_identities_provider_subject')
    )
    with op.batch_alter_table('autonomous_action_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
        batch_op.alter_column('action_type',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('previous_state_hash',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('action_signature',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.create_foreign_key('fk_autonomous_action_logs_agents', 'agents', ['target_agent_id'], ['id'])
        batch_op.create_foreign_key('fk_autonomous_action_logs_tenants', 'tenants', ['tenant_id'], ['id'])
        batch_op.drop_column('executed_at')

    with op.batch_alter_table('remediation_playbooks', schema=None) as batch_op:
        batch_op.alter_column('trigger_severity',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.create_foreign_key('fk_remediation_playbooks_tenants', 'tenants', ['tenant_id'], ['id'])
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remediation_playbooks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_constraint('fk_remediation_playbooks_tenants', type_='foreignkey')
        batch_op.alter_column('trigger_severity',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)

    with op.batch_alter_table('autonomous_action_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_constraint('fk_autonomous_action_logs_tenants', type_='foreignkey')
        batch_op.drop_constraint('fk_autonomous_action_logs_agents', type_='foreignkey')
        batch_op.alter_column('action_signature',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('previous_state_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
        batch_op.alter_column('action_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
        batch_op.drop_column('created_at')

    op.drop_table('agent_federated_identities')
    op.drop_table('external_identity_providers')
    # ### end Alembic commands ###
