"""Update Investigation models

Revision ID: 080cacfb3802
Revises: 14b760eabde7
Create Date: 2026-09-24 17:28:12.396288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '080cacfb3802'
down_revision: Union[str, Sequence[str], None] = '14b760eabde7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigation_audit_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('metadata_payload', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investigation_audit_records', schema=None) as batch_op:
        batch_op.create_index('ix_inv_audit_inv', ['investigation_id'], unique=False)
        batch_op.create_index('ix_inv_audit_tenant', ['tenant_id'], unique=False)

    op.create_table('investigation_findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investigation_findings', schema=None) as batch_op:
        batch_op.create_index('ix_inv_findings_tenant_inv', ['tenant_id', 'investigation_id'], unique=False)

    op.create_table('investigation_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investigation_notes', schema=None) as batch_op:
        batch_op.create_index('ix_inv_notes_tenant_inv', ['tenant_id', 'investigation_id'], unique=False)

    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('incident_id', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('alert_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('severity', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('assigned_to', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index('uix_investigations_incident_active', ['incident_id'], unique=True, sqlite_where=sa.text("status != 'CLOSED' AND status != 'RESOLVED'"), postgresql_where=sa.text("status != 'CLOSED' AND status != 'RESOLVED'"))
        batch_op.create_foreign_key('fk_investigations_alert_id', 'alerts', ['alert_id'], ['id'])
        batch_op.create_foreign_key('fk_investigations_incident_id', 'incidents', ['incident_id'], ['id'])
        batch_op.create_foreign_key('fk_investigations_users_id', 'users', ['assigned_to'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_investigations_alert_id', type_='foreignkey')
        batch_op.drop_constraint('fk_investigations_incident_id', type_='foreignkey')
        batch_op.drop_constraint('fk_investigations_users_id', type_='foreignkey')
        batch_op.drop_index('uix_investigations_incident_active', sqlite_where=sa.text("status != 'CLOSED' AND status != 'RESOLVED'"), postgresql_where=sa.text("status != 'CLOSED' AND status != 'RESOLVED'"))
        batch_op.drop_column('closed_at')
        batch_op.drop_column('resolved_at')
        batch_op.drop_column('assigned_to')
        batch_op.drop_column('severity')
        batch_op.drop_column('alert_id')
        batch_op.drop_column('incident_id')

    with op.batch_alter_table('investigation_notes', schema=None) as batch_op:
        batch_op.drop_index('ix_inv_notes_tenant_inv')

    op.drop_table('investigation_notes')
    with op.batch_alter_table('investigation_findings', schema=None) as batch_op:
        batch_op.drop_index('ix_inv_findings_tenant_inv')

    op.drop_table('investigation_findings')
    with op.batch_alter_table('investigation_audit_records', schema=None) as batch_op:
        batch_op.drop_index('ix_inv_audit_tenant')
        batch_op.drop_index('ix_inv_audit_inv')

    op.drop_table('investigation_audit_records')
    # ### end Alembic commands ###
