"""add_cryptographic_agent_identity

Revision ID: 145c2a40a75f
Revises: eae11445090e
Create Date: 2026-09-14 16:35:20.536834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '145c2a40a75f'
down_revision: Union[str, Sequence[str], None] = 'eae11445090e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('agent_credentials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('secret_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('active', 'revoked', name='credential_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_credentials_agent_id', 'agent_credentials', ['agent_id'], unique=False)
    
    with op.batch_alter_table('agents') as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.String(length=36), nullable=False, server_default='dummy'))
        batch_op.create_foreign_key('fk_agents_tenants', 'tenants', ['tenant_id'], ['id'])
        
    with op.batch_alter_table('authorization_decisions') as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.String(length=36), nullable=False, server_default='dummy'))
        batch_op.add_column(sa.Column('credential_id', sa.String(length=36), nullable=False, server_default='dummy'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authorization_decisions') as batch_op:
        batch_op.drop_column('credential_id')
        batch_op.drop_column('tenant_id')
        
    with op.batch_alter_table('agents') as batch_op:
        batch_op.drop_constraint('fk_agents_tenants', type_='foreignkey')
        batch_op.drop_column('tenant_id')
        
    op.drop_index('ix_agent_credentials_agent_id', table_name='agent_credentials')
    op.drop_table('agent_credentials')
    op.drop_table('tenants')
    # ### end Alembic commands ###
