"""Add Evidence model

Revision ID: 14b760eabde7
Revises: 039e60eb1a72
Create Date: 2026-09-24 17:07:24.021899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14b760eabde7'
down_revision: Union[str, Sequence[str], None] = '039e60eb1a72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=True),
    sa.Column('alert_id', sa.String(length=36), nullable=True),
    sa.Column('evidence_type', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('metadata_payload', sa.Text(), nullable=True),
    sa.Column('integrity_digest', sa.String(length=64), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'evidence_type', 'source_type', 'source_id', 'incident_id', name='uq_evidence_identity')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index('ix_evidence_alert', ['alert_id'], unique=False)
        batch_op.create_index('ix_evidence_incident', ['incident_id'], unique=False)
        batch_op.create_index('ix_evidence_tenant_type', ['tenant_id', 'evidence_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index('ix_evidence_tenant_type')
        batch_op.drop_index('ix_evidence_incident')
        batch_op.drop_index('ix_evidence_alert')

    op.drop_table('evidence')
    # ### end Alembic commands ###
