"""Add PolicyVersion single active index

Revision ID: 303775cb2bfe
Revises: 95f2281fc5f1
Create Date: 2026-09-17 12:04:32.316397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '303775cb2bfe'
down_revision: Union[str, Sequence[str], None] = '95f2281fc5f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policy_versions', schema=None) as batch_op:
        batch_op.create_index('ix_policy_versions_single_active', ['policy_id'], unique=True, sqlite_where=sa.text("status = 'active'"), postgresql_where=sa.text("status = 'active'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policy_versions', schema=None) as batch_op:
        batch_op.drop_index('ix_policy_versions_single_active', sqlite_where=sa.text("status = 'active'"), postgresql_where=sa.text("status = 'active'"))

    # ### end Alembic commands ###
