"""add_analytics_models

Revision ID: 3b546e6d0bc4
Revises: fcda172d1804
Create Date: 2026-09-17 14:43:55.909898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b546e6d0bc4'
down_revision: Union[str, Sequence[str], None] = 'fcda172d1804'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_agent_security_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('total_events', sa.Integer(), nullable=False),
    sa.Column('policy_denials', sa.Integer(), nullable=False),
    sa.Column('capability_denials', sa.Integer(), nullable=False),
    sa.Column('critical_risks', sa.Integer(), nullable=False),
    sa.Column('incidents_triggered', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'agent_id', 'metric_date', name='uq_daily_agent_metric')
    )
    op.create_table('daily_tenant_security_metrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('total_incidents', sa.Integer(), nullable=False),
    sa.Column('active_investigations', sa.Integer(), nullable=False),
    sa.Column('unique_agents_flagged', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'metric_date', name='uq_daily_tenant_metric')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_tenant_security_metrics')
    op.drop_table('daily_agent_security_metrics')
    # ### end Alembic commands ###
