"""agent_tool_capabilities

Revision ID: 4256de45b869
Revises: 840e15e68308
Create Date: 2026-09-14 17:47:27.450122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4256de45b869'
down_revision: Union[str, Sequence[str], None] = '840e15e68308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capabilities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_capabilities_tenant_name')
    )
    op.create_table('tools',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_tools_tenant_name')
    )
    op.create_table('agent_capabilities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('capability_id', sa.String(length=36), nullable=False),
    sa.Column('resource_scope', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_capabilities', schema=None) as batch_op:
        batch_op.create_index('ix_agent_capabilities_agent_id', ['agent_id'], unique=False)

    op.create_table('tool_action_capabilities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tool_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('capability_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tool_id', 'action', name='uq_tool_action_capabilities_tool_action')
    )
    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tool_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('capability_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_executions_tools', 'tools', ['tool_id'], ['id'])
        batch_op.create_foreign_key('fk_executions_capabilities', 'capabilities', ['capability_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_executions_capabilities', type_='foreignkey')
        batch_op.drop_constraint('fk_executions_tools', type_='foreignkey')
        batch_op.drop_column('capability_id')
        batch_op.drop_column('tool_id')

    op.drop_table('tool_action_capabilities')
    with op.batch_alter_table('agent_capabilities', schema=None) as batch_op:
        batch_op.drop_index('ix_agent_capabilities_agent_id')

    op.drop_table('agent_capabilities')
    op.drop_table('tools')
    op.drop_table('capabilities')
    # ### end Alembic commands ###
