"""add_agent_trust_and_delegation

Revision ID: 4411e1b2945b
Revises: 080cacfb3802
Create Date: 2026-09-25 18:11:43.295683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4411e1b2945b'
down_revision: Union[str, Sequence[str], None] = '080cacfb3802'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_trust_relationships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('source_agent_id', sa.String(length=36), nullable=False),
    sa.Column('target_agent_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('trust_scope', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'REVOKED', 'EXPIRED')", name='ck_agent_trust_status_valid'),
    sa.CheckConstraint('source_agent_id != target_agent_id', name='ck_agent_trust_no_self_trust'),
    sa.ForeignKeyConstraint(['source_agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_agent_id', 'target_agent_id', name='uq_agent_trust_tenant_source_target')
    )
    with op.batch_alter_table('agent_trust_relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_trust_relationships_source_agent_id'), ['source_agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_trust_relationships_target_agent_id'), ['target_agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_trust_relationships_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('agent_delegations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('delegator_agent_id', sa.String(length=36), nullable=False),
    sa.Column('delegate_agent_id', sa.String(length=36), nullable=False),
    sa.Column('trust_relationship_id', sa.String(length=36), nullable=False),
    sa.Column('action_scope', sa.JSON(), nullable=False),
    sa.Column('resource_scope', sa.JSON(), nullable=False),
    sa.Column('capability_scope', sa.JSON(), nullable=False),
    sa.Column('parent_delegation_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signature', sa.String(length=512), nullable=False),
    sa.Column('signing_key_id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'REVOKED', 'EXPIRED')", name='ck_agent_delegation_status_valid'),
    sa.CheckConstraint('delegator_agent_id != delegate_agent_id', name='ck_agent_delegation_no_self_delegation'),
    sa.CheckConstraint('expires_at > issued_at', name='ck_agent_delegation_expires_after_issued'),
    sa.ForeignKeyConstraint(['delegate_agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['delegator_agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_delegation_id'], ['agent_delegations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['signing_key_id'], ['agent_signing_keys.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trust_relationship_id'], ['agent_trust_relationships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_delegations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_delegations_delegate_agent_id'), ['delegate_agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_delegations_delegator_agent_id'), ['delegator_agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_delegations_parent_delegation_id'), ['parent_delegation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_delegations_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_delegations_trust_relationship_id'), ['trust_relationship_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_delegations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_delegations_trust_relationship_id'))
        batch_op.drop_index(batch_op.f('ix_agent_delegations_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_agent_delegations_parent_delegation_id'))
        batch_op.drop_index(batch_op.f('ix_agent_delegations_delegator_agent_id'))
        batch_op.drop_index(batch_op.f('ix_agent_delegations_delegate_agent_id'))

    op.drop_table('agent_delegations')
    with op.batch_alter_table('agent_trust_relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_trust_relationships_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_agent_trust_relationships_target_agent_id'))
        batch_op.drop_index(batch_op.f('ix_agent_trust_relationships_source_agent_id'))

    op.drop_table('agent_trust_relationships')
    # ### end Alembic commands ###
