"""Add distributed security domains

Revision ID: 4770667aeb27
Revises: 4411e1b2945b
Create Date: 2026-09-26 18:12:13.324101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4770667aeb27'
down_revision: Union[str, Sequence[str], None] = '4411e1b2945b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_security_domains',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uix_tenant_domain_name')
    )
    with op.batch_alter_table('agent_security_domains', schema=None) as batch_op:
        batch_op.create_index('ix_agent_security_domains_tenant', ['tenant_id'], unique=False)

    op.create_table('agent_security_domain_memberships',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('domain_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['domain_id'], ['agent_security_domains.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_id', 'agent_id', name='uix_domain_agent')
    )
    with op.batch_alter_table('agent_security_domain_memberships', schema=None) as batch_op:
        batch_op.create_index('ix_agent_security_domain_memberships_agent', ['agent_id'], unique=False)
        batch_op.create_index('ix_agent_security_domain_memberships_domain', ['domain_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_security_domain_memberships', schema=None) as batch_op:
        batch_op.drop_index('ix_agent_security_domain_memberships_domain')
        batch_op.drop_index('ix_agent_security_domain_memberships_agent')

    op.drop_table('agent_security_domain_memberships')
    with op.batch_alter_table('agent_security_domains', schema=None) as batch_op:
        batch_op.drop_index('ix_agent_security_domains_tenant')

    op.drop_table('agent_security_domains')
    # ### end Alembic commands ###
