"""add_risk_assessments

Revision ID: 542dd7a13cc0
Revises: 145c2a40a75f
Create Date: 2026-09-14 17:05:38.457521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '542dd7a13cc0'
down_revision: Union[str, Sequence[str], None] = '145c2a40a75f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('credential_id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=32), nullable=False),
    sa.Column('factors', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('evaluation_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.create_index('ix_risk_assessments_request_id', ['request_id'], unique=False)

    with op.batch_alter_table('authorization_decisions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('risk_assessment_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_authorization_decisions_risk', 'risk_assessments', ['risk_assessment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authorization_decisions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_authorization_decisions_risk', type_='foreignkey')
        batch_op.drop_column('risk_assessment_id')

    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.drop_index('ix_risk_assessments_request_id')

    op.drop_table('risk_assessments')
    # ### end Alembic commands ###
