"""Add tenant_id and status to policies

Revision ID: 5d97c73fd1bc
Revises: c0fbc7dc677e
Create Date: 2026-09-16 20:39:54.307159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d97c73fd1bc'
down_revision: Union[str, Sequence[str], None] = 'c0fbc7dc677e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.String(length=36), nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_policies_name'), type_='unique')
        batch_op.create_unique_constraint('uq_policies_tenant_name', ['tenant_id', 'name'])
        batch_op.create_foreign_key('fk_policies_tenant_id_tenants', 'tenants', ['tenant_id'], ['id'])

    with op.batch_alter_table('policy_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('status', sa.Enum('draft', 'review', 'approved', 'published', 'active', 'deprecated', name='policy_version_status'), nullable=False))
        batch_op.create_foreign_key('fk_policy_versions_tenant_id_tenants', 'tenants', ['tenant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('policy_versions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_policy_versions_tenant_id_tenants', type_='foreignkey')
        batch_op.drop_column('status')
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.drop_constraint('fk_policies_tenant_id_tenants', type_='foreignkey')
        batch_op.drop_constraint('uq_policies_tenant_name', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_policies_name'), ['name'])
        batch_op.drop_column('tenant_id')

    # ### end Alembic commands ###
