"""add_security_events

Revision ID: 5fcc45698800
Revises: 303775cb2bfe
Create Date: 2026-09-17 13:24:01.129166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fcc45698800'
down_revision: Union[str, Sequence[str], None] = '303775cb2bfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('credential_id', sa.String(length=36), nullable=True),
    sa.Column('tool_id', sa.String(length=36), nullable=True),
    sa.Column('policy_id', sa.String(length=36), nullable=True),
    sa.Column('policy_version_id', sa.String(length=36), nullable=True),
    sa.Column('execution_id', sa.String(length=36), nullable=True),
    sa.Column('authorization_decision_id', sa.String(length=36), nullable=True),
    sa.Column('correlation_id', sa.String(length=255), nullable=True),
    sa.Column('request_id', sa.String(length=255), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=True),
    sa.Column('metadata_payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('security_events', schema=None) as batch_op:
        batch_op.create_index('ix_security_events_request', ['request_id'], unique=False)
        batch_op.create_index('ix_security_events_tenant_agent_time', ['tenant_id', 'agent_id', 'occurred_at'], unique=False)
        batch_op.create_index('ix_security_events_tenant_correlation', ['tenant_id', 'correlation_id'], unique=False)
        batch_op.create_index('ix_security_events_tenant_type_time', ['tenant_id', 'event_type', 'occurred_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security_events', schema=None) as batch_op:
        batch_op.drop_index('ix_security_events_tenant_type_time')
        batch_op.drop_index('ix_security_events_tenant_correlation')
        batch_op.drop_index('ix_security_events_tenant_agent_time')
        batch_op.drop_index('ix_security_events_request')

    op.drop_table('security_events')
    # ### end Alembic commands ###
