"""Add request_fingerprint to executions

Revision ID: 795422a9e2d8
Revises: 4770667aeb27
Create Date: 2026-09-30 19:15:12.629945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '795422a9e2d8'
down_revision: Union[str, Sequence[str], None] = '4770667aeb27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_fingerprint', sa.String(length=64), server_default='', nullable=False))

    with op.batch_alter_table('request_replay_records', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_request_replay_records_identity'), type_='unique')
        batch_op.create_unique_constraint('uq_request_replay_records_tenant_request', ['tenant_id', 'request_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_replay_records', schema=None) as batch_op:
        batch_op.drop_constraint('uq_request_replay_records_tenant_request', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_request_replay_records_identity'), ['tenant_id', 'agent_id', 'request_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.drop_column('request_fingerprint')

    # ### end Alembic commands ###
