"""add_idempotency_and_reconciliation

Revision ID: 840e15e68308
Revises: dd6686e52ad6
Create Date: 2026-09-14 17:38:13.019739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '840e15e68308'
down_revision: Union[str, Sequence[str], None] = 'dd6686e52ad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_reconciliations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('execution_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('reconciler_type', sa.String(length=128), nullable=False),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('error_info', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('execution_reconciliations', schema=None) as batch_op:
        batch_op.create_index('ix_execution_reconciliations_execution_id', ['execution_id'], unique=False)

    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_executions_tenant_request', ['tenant_id', 'request_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_executions_tenant_request', type_='unique')

    with op.batch_alter_table('execution_reconciliations', schema=None) as batch_op:
        batch_op.drop_index('ix_execution_reconciliations_execution_id')

    op.drop_table('execution_reconciliations')
    # ### end Alembic commands ###
