"""add_outbox_events

Revision ID: 8bd8f065fb97
Revises: f17881f7fc17
Create Date: 2026-09-14 15:08:44.298520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bd8f065fb97'
down_revision: Union[str, Sequence[str], None] = 'f17881f7fc17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('aggregate_type', sa.String(length=255), nullable=False),
    sa.Column('aggregate_id', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'published', 'failed', 'dead_letter', name='outbox_status'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outbox_events_correlation_id', 'outbox_events', ['correlation_id'], unique=False)
    op.create_index('ix_outbox_events_status_available_at', 'outbox_events', ['status', 'available_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_outbox_events_status_available_at', table_name='outbox_events')
    op.drop_index('ix_outbox_events_correlation_id', table_name='outbox_events')
    op.drop_table('outbox_events')
    
    # Drop enum type in postgresql
    bind = op.get_bind()
    if bind.engine.name == 'postgresql':
        op.execute("DROP TYPE IF EXISTS outbox_status")
    # ### end Alembic commands ###
