"""Add PolicyAuditRecord

Revision ID: 95f2281fc5f1
Revises: 5d97c73fd1bc
Create Date: 2026-09-17 08:05:13.719962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95f2281fc5f1'
down_revision: Union[str, Sequence[str], None] = '5d97c73fd1bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_audit_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('policy_id', sa.String(length=36), nullable=False),
    sa.Column('policy_version_id', sa.String(length=36), nullable=True),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('credential_id', sa.String(length=36), nullable=True),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('before_state', sa.Text(), nullable=True),
    sa.Column('after_state', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('correlation_id', sa.String(length=36), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policy_audit_records', schema=None) as batch_op:
        batch_op.create_index('ix_policy_audit_correlation_id', ['correlation_id'], unique=False)
        batch_op.create_index('ix_policy_audit_occurred_at', ['occurred_at'], unique=False)
        batch_op.create_index('ix_policy_audit_policy_id', ['policy_id'], unique=False)
        batch_op.create_index('ix_policy_audit_policy_version_id', ['policy_version_id'], unique=False)
        batch_op.create_index('ix_policy_audit_request_id', ['request_id'], unique=False)
        batch_op.create_index('ix_policy_audit_tenant_id', ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policy_audit_records', schema=None) as batch_op:
        batch_op.drop_index('ix_policy_audit_tenant_id')
        batch_op.drop_index('ix_policy_audit_request_id')
        batch_op.drop_index('ix_policy_audit_policy_version_id')
        batch_op.drop_index('ix_policy_audit_policy_id')
        batch_op.drop_index('ix_policy_audit_occurred_at')
        batch_op.drop_index('ix_policy_audit_correlation_id')

    op.drop_table('policy_audit_records')
    # ### end Alembic commands ###
