"""add_distributed_locks

Revision ID: a7d554e823e1
Revises: 06a7dd6a9514
Create Date: 2026-09-17 15:20:51.857353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7d554e823e1'
down_revision: Union[str, Sequence[str], None] = '06a7dd6a9514'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engine_nodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('public_key', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cryptographic_leases',
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('owner_node_id', sa.String(length=36), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cryptographic_proof', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_node_id'], ['engine_nodes.id'], ),
    sa.PrimaryKeyConstraint('resource_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cryptographic_leases')
    op.drop_table('engine_nodes')
    # ### end Alembic commands ###
