"""add_ai_security_models

Revision ID: b1982f303fe1
Revises: a7d554e823e1
Create Date: 2026-09-17 15:34:32.966480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1982f303fe1'
down_revision: Union[str, Sequence[str], None] = 'a7d554e823e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_action_velocity_states',
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('tokens', sa.Float(), nullable=False),
    sa.Column('last_refill', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_out', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_table('ai_agent_attestations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('model_hash', sa.String(length=255), nullable=False),
    sa.Column('tee_signature', sa.String(length=1024), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id')
    )
    op.create_table('ai_pending_high_risk_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('action_payload', sa.Text(), nullable=False),
    sa.Column('required_signatures', sa.Integer(), nullable=False),
    sa.Column('collected_signatures', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_pending_high_risk_actions')
    op.drop_table('ai_agent_attestations')
    op.drop_table('ai_action_velocity_states')
    # ### end Alembic commands ###
