"""add_agent_signing_keys

Revision ID: c0fbc7dc677e
Revises: 4256de45b869
Create Date: 2026-09-14 19:00:20.084714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0fbc7dc677e'
down_revision: Union[str, Sequence[str], None] = '4256de45b869'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_signing_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('public_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('active', 'revoked', name='signing_key_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_signing_keys', schema=None) as batch_op:
        batch_op.create_index('ix_agent_signing_keys_agent_id', ['agent_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_signing_keys', schema=None) as batch_op:
        batch_op.drop_index('ix_agent_signing_keys_agent_id')

    op.drop_table('agent_signing_keys')
    # ### end Alembic commands ###
