"""immutable_policy_versioning

Revision ID: cf4d079607c7
Revises: b721d641a425
Create Date: 2026-09-14 14:38:12.292083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf4d079607c7'
down_revision: Union[str, Sequence[str], None] = 'b721d641a425'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('policy_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('effect', sa.Enum('allow', 'deny', name='policy_effect'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('resource', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("effect IN ('allow', 'deny')", name='ck_policy_versions_effect'),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_id', 'version', name='uq_policy_versions_policy_id_version')
    )
    
    with op.batch_alter_table('authorization_decisions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('policy_version_id', sa.String(length=36), nullable=True))

    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_version_id', sa.String(length=36), nullable=True))
        
    # Data Migration
    import uuid
    conn = op.get_bind()
    policies = conn.execute(sa.text("SELECT id, effect, priority, action, resource, created_at FROM policies")).fetchall()
    for p in policies:
        version_id = str(uuid.uuid4())
        conn.execute(
            sa.text("""
                INSERT INTO policy_versions (id, policy_id, version, effect, priority, action, resource, created_at)
                VALUES (:id, :policy_id, 1, :effect, :priority, :action, :resource, :created_at)
            """),
            {"id": version_id, "policy_id": p[0], "effect": p[1], "priority": p[2], "action": p[3], "resource": p[4], "created_at": p[5]}
        )
        conn.execute(
            sa.text("UPDATE policies SET active_version_id = :version_id WHERE id = :id"),
            {"version_id": version_id, "id": p[0]}
        )

    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.drop_constraint('ck_policies_effect', type_='check')
        batch_op.create_unique_constraint('uq_policies_name', ['name'])
        batch_op.create_foreign_key('fk_policy_active_version', 'policy_versions', ['active_version_id'], ['id'])
        batch_op.drop_column('resource')
        batch_op.drop_column('priority')
        batch_op.drop_column('effect')
        batch_op.drop_column('action')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('effect', sa.VARCHAR(length=5), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('resource', sa.VARCHAR(length=255), nullable=True))
        
    conn = op.get_bind()
    versions = conn.execute(sa.text("SELECT id, policy_id, effect, priority, action, resource FROM policy_versions WHERE version = 1")).fetchall()
    for v in versions:
        conn.execute(
            sa.text("UPDATE policies SET effect = :effect, priority = :priority, action = :action, resource = :resource WHERE id = :policy_id"),
            {"effect": v[2], "priority": v[3], "action": v[4], "resource": v[5], "policy_id": v[1]}
        )
        
    with op.batch_alter_table('policies', schema=None) as batch_op:
        batch_op.drop_constraint('fk_policy_active_version', type_='foreignkey')
        batch_op.drop_constraint('uq_policies_name', type_='unique')
        batch_op.create_check_constraint('ck_policies_effect', condition="effect IN ('allow', 'deny')")
        batch_op.drop_column('active_version_id')

    with op.batch_alter_table('authorization_decisions', schema=None) as batch_op:
        batch_op.drop_column('policy_version_id')
        
    op.drop_table('policy_versions')
    # ### end Alembic commands ###
