"""add_execution_records

Revision ID: dd6686e52ad6
Revises: 542dd7a13cc0
Create Date: 2026-09-14 17:21:09.843998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd6686e52ad6'
down_revision: Union[str, Sequence[str], None] = '542dd7a13cc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('executions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('authorization_decision_id', sa.String(length=36), nullable=False),
    sa.Column('risk_assessment_id', sa.String(length=36), nullable=True),
    sa.Column('policy_id', sa.String(length=36), nullable=True),
    sa.Column('policy_version_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('resource', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['authorization_decision_id'], ['authorization_decisions.id'], ),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_versions.id'], ),
    sa.ForeignKeyConstraint(['risk_assessment_id'], ['risk_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.create_index('ix_executions_authorization_decision_id', ['authorization_decision_id'], unique=False)
        batch_op.create_index('ix_executions_request_id', ['request_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.drop_index('ix_executions_request_id')
        batch_op.drop_index('ix_executions_authorization_decision_id')

    op.drop_table('executions')
    # ### end Alembic commands ###
