"""add outbox event leases

Revision ID: eae11445090e
Revises: 8bd8f065fb97
Create Date: 2026-09-14 15:24:12.600530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eae11445090e'
down_revision: Union[str, Sequence[str], None] = '8bd8f065fb97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox_events', sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('outbox_events', sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('outbox_events', sa.Column('claim_token', sa.String(length=36), nullable=True))
    op.create_index('ix_outbox_events_processing_lease', 'outbox_events', ['status', 'lease_until'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_outbox_events_processing_lease', table_name='outbox_events')
    op.drop_column('outbox_events', 'claim_token')
    op.drop_column('outbox_events', 'lease_until')
    op.drop_column('outbox_events', 'claimed_at')
    # ### end Alembic commands ###
