"""add_autonomous_remediation

Revision ID: f929ce0b171e
Revises: 3b546e6d0bc4
Create Date: 2026-09-17 14:57:25.712918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f929ce0b171e'
down_revision: Union[str, Sequence[str], None] = '3b546e6d0bc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remediation_playbooks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('trigger_severity', sa.String(length=32), nullable=False),
    sa.Column('action_types', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('autonomous_action_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('target_agent_id', sa.String(length=36), nullable=False),
    sa.Column('previous_state_hash', sa.String(length=64), nullable=False),
    sa.Column('action_signature', sa.Text(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('autonomous_action_logs')
    op.drop_table('remediation_playbooks')
    # ### end Alembic commands ###
